"""
validate_labels.py

Validation utilities for Category and Section labels generated by the LLM.

This module is responsible for:
- Defining the permitted CNN Category and Section labels.
- Providing the JSON schema sent to Ollama.
- Parsing the LLM's JSON response.
- Normalizing minor formatting differences.
- Rejecting missing, malformed, or invalid labels.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from typing import Any


VALID_CATEGORIES: tuple[str, ...] = (
    "news",
    "business",
    "health",
    "entertainment",
    "sport",
    "politics",
)


VALID_SECTIONS: tuple[str, ...] = (
    "world",
    "asia",
    "investing",
    "business",
    "media",
    "energy",
    "tech",
    "business-food",
    "economy",
    "cars",
    "health",
    "entertainment",
    "us",
    "golf",
    "sport",
    "motorsport",
    "football",
    "tennis",
    "africa",
    "opinions",
    "europe",
    "china",
    "politics",
    "success",
    "homes",
    "business-money",
    "perspectives",
    "movies",
    "celebrities",
    "living",
    "americas",
    "middleeast",
    "india",
    "weather",
    "intl_world",
    "uk",
    "australia",
)


class LabelValidationError(ValueError):
    """Raised when an LLM response does not contain valid labels."""


@dataclass(frozen=True)
class ValidatedLabels:
    """
    Validated Category and Section labels.

    Attributes
    ----------
    category:
        Valid CNN Category label.

    section:
        Valid CNN Section label.
    """

    category: str
    section: str


def get_label_response_schema() -> dict[str, Any]:
    """
    Return the JSON schema used to constrain Ollama output.

    Returns
    -------
    dict[str, Any]
        JSON schema requiring exactly one valid Category and Section.
    """
    return {
        "type": "object",
        "properties": {
            "category": {
                "type": "string",
                "enum": list(VALID_CATEGORIES),
            },
            "section": {
                "type": "string",
                "enum": list(VALID_SECTIONS),
            },
        },
        "required": [
            "category",
            "section",
        ],
        "additionalProperties": False,
    }


def normalize_label(value: str) -> str:
    """
    Normalize minor formatting differences in an LLM-generated label.

    Normalization includes:
    - Removing leading and trailing whitespace.
    - Converting text to lowercase.
    - Converting spaces to hyphens.

    Parameters
    ----------
    value:
        Label returned by the LLM.

    Returns
    -------
    str
        Normalized label.

    Examples
    --------
    ``" Business "`` becomes ``"business"``.

    ``"Business Food"`` becomes ``"business-food"``.
    """
    return value.strip().lower().replace(" ", "-")


def parse_label_response(response_content: str) -> ValidatedLabels:
    """
    Parse and validate an LLM-generated JSON response.

    Parameters
    ----------
    response_content:
        Raw JSON text returned by Ollama.

    Returns
    -------
    ValidatedLabels
        Validated and normalized Category and Section labels.

    Raises
    ------
    LabelValidationError
        If the response is empty, malformed, incomplete, or contains
        labels outside the permitted sets.
    """
    if not response_content or not response_content.strip():
        raise LabelValidationError("The LLM response is empty.")

    try:
        parsed_response = json.loads(response_content)

    except json.JSONDecodeError as error:
        raise LabelValidationError(
            f"The LLM response is not valid JSON: {error.msg}"
        ) from error

    if not isinstance(parsed_response, dict):
        raise LabelValidationError(
            "The LLM response must be a JSON object."
        )

    unexpected_fields = set(parsed_response) - {"category", "section"}

    if unexpected_fields:
        unexpected = ", ".join(sorted(unexpected_fields))

        raise LabelValidationError(
            f"The LLM response contains unexpected fields: {unexpected}"
        )

    missing_fields = {
        field
        for field in ("category", "section")
        if field not in parsed_response
    }

    if missing_fields:
        missing = ", ".join(sorted(missing_fields))

        raise LabelValidationError(
            f"The LLM response is missing required fields: {missing}"
        )

    category_value = parsed_response["category"]
    section_value = parsed_response["section"]

    if not isinstance(category_value, str):
        raise LabelValidationError(
            "The Category label must be a string."
        )

    if not isinstance(section_value, str):
        raise LabelValidationError(
            "The Section label must be a string."
        )

    category = normalize_label(category_value)
    section = normalize_label(section_value)

    if category not in VALID_CATEGORIES:
        raise LabelValidationError(
            f"Invalid Category label: '{category_value}'. "
            f"Expected one of: {', '.join(VALID_CATEGORIES)}"
        )

    if section not in VALID_SECTIONS:
        raise LabelValidationError(
            f"Invalid Section label: '{section_value}'. "
            f"Expected one of: {', '.join(VALID_SECTIONS)}"
        )

    return ValidatedLabels(
        category=category,
        section=section,
    )


def labels_are_valid(response_content: str) -> bool:
    """
    Return whether an LLM response contains valid labels.

    This convenience function suppresses validation errors. Use
    ``parse_label_response`` when the specific reason for failure is needed.

    Parameters
    ----------
    response_content:
        Raw response returned by the LLM.

    Returns
    -------
    bool
        True when both labels are valid; otherwise False.
    """
    try:
        parse_label_response(response_content)
        return True

    except LabelValidationError:
        return False