"""
09_semantic_neighbor_analysis.py

Analyze local semantic structure in the CNN News Articles dataset using the
Sentence-BERT embeddings generated by 08_generate_sentence_embeddings.py.

This stage preserves the nearest-neighbour method developed in the project
notebook:

- cosine-distance nearest-neighbour retrieval,
- five non-self neighbours per article,
- article-level neighbour headlines and cosine similarities,
- same-Category neighbour ratio.

The integrated pipeline extends that method by also evaluating:

- same-Section neighbour ratios,
- per-class neighbour consistency,
- similarity distributions,
- original CNN labels versus LLM-generated labels on the training set.

Inputs:
- data/processed/sentence_embeddings/full_embeddings.npy
- data/processed/sentence_embeddings/full_metadata.csv
- data/processed/sentence_embeddings/train_embeddings.npy
- data/processed/sentence_embeddings/train_metadata.csv
- data/processed/sentence_embeddings/embedding_manifest.json
- data/interim/train_original.csv
- data/interim/train_llm_labeled.csv

Outputs:
- results/tables/semantic_neighbors/full_neighbor_results.csv
- results/tables/semantic_neighbors/full_neighbor_pairs.csv
- results/tables/semantic_neighbors/full_class_consistency.csv
- results/tables/semantic_neighbors/train_label_source_summary.csv
- results/tables/semantic_neighbors/train_class_consistency.csv
- results/tables/semantic_neighbors/semantic_neighbor_summary.csv
- results/figures/semantic_neighbors/*.png

The script is read-only with respect to all existing datasets and embedding
artifacts.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import sys
from typing import Any, Iterable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml
from sklearn.neighbors import NearestNeighbors


# ---------------------------------------------------------------------------
# Project paths and imports
# ---------------------------------------------------------------------------

SRC_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SRC_DIR.parent
CONFIG_PATH = PROJECT_ROOT / "config" / "config.yaml"

EMBEDDING_DIRECTORY = (
    PROJECT_ROOT / "data" / "processed" / "sentence_embeddings"
)
FULL_EMBEDDINGS_PATH = EMBEDDING_DIRECTORY / "full_embeddings.npy"
TRAIN_EMBEDDINGS_PATH = EMBEDDING_DIRECTORY / "train_embeddings.npy"
FULL_METADATA_PATH = EMBEDDING_DIRECTORY / "full_metadata.csv"
TRAIN_METADATA_PATH = EMBEDDING_DIRECTORY / "train_metadata.csv"
MANIFEST_PATH = EMBEDDING_DIRECTORY / "embedding_manifest.json"

TABLE_DIRECTORY = PROJECT_ROOT / "results" / "tables" / "semantic_neighbors"
FIGURE_DIRECTORY = (
    PROJECT_ROOT / "results" / "figures" / "semantic_neighbors"
)

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from utils.io import read_csv, write_csv
from utils.logging import get_logger


logger = get_logger(
    name=__name__,
    log_directory=PROJECT_ROOT / "logs",
    log_file="project.log",
)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ID_COLUMN = "Index"
HEADLINE_COLUMN = "Headline"
CATEGORY_COLUMN = "Category"
SECTION_COLUMN = "Section"
LABEL_COLUMNS: tuple[str, str] = (CATEGORY_COLUMN, SECTION_COLUMN)

DEFAULT_NEIGHBOR_COUNT = 5
DEFAULT_N_JOBS = -1
DEFAULT_FIGURE_DPI = 300
DEFAULT_TOP_CLASSES = 20


class SemanticNeighborAnalysisError(RuntimeError):
    """Raised when semantic-neighbour analysis cannot be completed safely."""


@dataclass(frozen=True)
class NeighborSettings:
    """Resolved configuration for semantic-neighbour analysis."""

    neighbor_count: int
    n_jobs: int
    figure_dpi: int
    top_classes: int


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def load_config(config_path: Path) -> dict[str, Any]:
    """Load the project configuration."""
    if not config_path.exists():
        raise SemanticNeighborAnalysisError(
            f"Configuration file not found: {config_path}"
        )

    try:
        with config_path.open("r", encoding="utf-8") as file:
            config = yaml.safe_load(file)
    except yaml.YAMLError as error:
        raise SemanticNeighborAnalysisError(
            f"Could not parse the configuration file: {error}"
        ) from error

    if not isinstance(config, dict):
        raise SemanticNeighborAnalysisError(
            "The configuration file must contain a YAML mapping."
        )

    dataset_config = config.get("dataset")
    if not isinstance(dataset_config, dict):
        raise SemanticNeighborAnalysisError(
            "The configuration must contain a 'dataset' section."
        )

    required_settings = {"train_file", "llm_train_file"}
    missing_settings = required_settings - set(dataset_config)
    if missing_settings:
        missing = ", ".join(sorted(missing_settings))
        raise SemanticNeighborAnalysisError(
            f"Missing dataset settings in config.yaml: {missing}"
        )

    return config


def resolve_project_path(configured_path: str) -> Path:
    """Resolve a configured path relative to the project root."""
    path = Path(configured_path)
    return path if path.is_absolute() else PROJECT_ROOT / path


def get_neighbor_settings(config: dict[str, Any]) -> NeighborSettings:
    """Resolve optional settings while retaining notebook-compatible defaults."""
    raw_settings = config.get("semantic_neighbors", {})
    if raw_settings is None:
        raw_settings = {}
    if not isinstance(raw_settings, dict):
        raise SemanticNeighborAnalysisError(
            "semantic_neighbors must be a YAML mapping when provided."
        )

    neighbor_count = raw_settings.get(
        "neighbor_count", DEFAULT_NEIGHBOR_COUNT
    )
    n_jobs = raw_settings.get("n_jobs", DEFAULT_N_JOBS)
    figure_dpi = raw_settings.get("figure_dpi", DEFAULT_FIGURE_DPI)
    top_classes = raw_settings.get("top_classes", DEFAULT_TOP_CLASSES)

    if not isinstance(neighbor_count, int) or neighbor_count < 1:
        raise SemanticNeighborAnalysisError(
            "semantic_neighbors.neighbor_count must be a positive integer."
        )
    if not isinstance(n_jobs, int) or n_jobs == 0:
        raise SemanticNeighborAnalysisError(
            "semantic_neighbors.n_jobs must be a non-zero integer."
        )
    if not isinstance(figure_dpi, int) or figure_dpi < 72:
        raise SemanticNeighborAnalysisError(
            "semantic_neighbors.figure_dpi must be an integer of at least 72."
        )
    if not isinstance(top_classes, int) or top_classes < 1:
        raise SemanticNeighborAnalysisError(
            "semantic_neighbors.top_classes must be a positive integer."
        )

    return NeighborSettings(
        neighbor_count=neighbor_count,
        n_jobs=n_jobs,
        figure_dpi=figure_dpi,
        top_classes=top_classes,
    )


# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------

def require_files(paths: Iterable[Path]) -> None:
    """Require every input artifact before starting analysis."""
    missing = [str(path) for path in paths if not path.exists()]
    if missing:
        raise SemanticNeighborAnalysisError(
            "Required semantic-analysis inputs are missing:\n- "
            + "\n- ".join(missing)
            + "\nRun 08_generate_sentence_embeddings.py first."
        )


def load_manifest() -> dict[str, Any]:
    """Load and validate the embedding manifest."""
    try:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise SemanticNeighborAnalysisError(
            f"Could not read the embedding manifest: {error}"
        ) from error

    if not isinstance(manifest, dict):
        raise SemanticNeighborAnalysisError(
            "The embedding manifest must contain a JSON object."
        )
    return manifest


def validate_metadata(metadata: pd.DataFrame, dataset_name: str) -> None:
    """Validate metadata required for semantic-neighbour reporting."""
    required_columns = {
        ID_COLUMN,
        "embedding_row",
        HEADLINE_COLUMN,
        CATEGORY_COLUMN,
        SECTION_COLUMN,
    }
    missing_columns = required_columns - set(metadata.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise SemanticNeighborAnalysisError(
            f"The {dataset_name} metadata is missing columns: {missing}"
        )

    if metadata.empty:
        raise SemanticNeighborAnalysisError(
            f"The {dataset_name} metadata contains no rows."
        )
    if metadata[ID_COLUMN].duplicated().any():
        raise SemanticNeighborAnalysisError(
            f"The {dataset_name} metadata contains duplicate {ID_COLUMN} values."
        )

    expected_rows = np.arange(len(metadata))
    actual_rows = metadata["embedding_row"].to_numpy()
    if not np.array_equal(actual_rows, expected_rows):
        raise SemanticNeighborAnalysisError(
            f"The {dataset_name} metadata is not in embedding-row order."
        )

    for label_column in LABEL_COLUMNS:
        if metadata[label_column].isna().any():
            raise SemanticNeighborAnalysisError(
                f"The {dataset_name} metadata contains missing {label_column} labels."
            )


def validate_embeddings(
    embeddings: np.ndarray,
    metadata: pd.DataFrame,
    dataset_name: str,
    expected_dimension: int | None,
) -> None:
    """Validate matrix shape, values, and row alignment."""
    if embeddings.ndim != 2:
        raise SemanticNeighborAnalysisError(
            f"The {dataset_name} embeddings must be a two-dimensional matrix."
        )
    if embeddings.shape[0] != len(metadata):
        raise SemanticNeighborAnalysisError(
            f"The {dataset_name} embedding and metadata row counts differ."
        )
    if expected_dimension is not None and embeddings.shape[1] != expected_dimension:
        raise SemanticNeighborAnalysisError(
            f"The {dataset_name} embedding dimension does not match the manifest."
        )
    if not np.isfinite(embeddings).all():
        raise SemanticNeighborAnalysisError(
            f"The {dataset_name} embeddings contain non-finite values."
        )


def align_training_labels(
    train_metadata: pd.DataFrame,
    train_original: pd.DataFrame,
    train_llm: pd.DataFrame,
) -> pd.DataFrame:
    """Return row-aligned original and LLM labels for training articles."""
    required_columns = {ID_COLUMN, CATEGORY_COLUMN, SECTION_COLUMN}
    for dataframe, name in (
        (train_original, "original training dataset"),
        (train_llm, "LLM-labelled training dataset"),
    ):
        missing = required_columns - set(dataframe.columns)
        if missing:
            raise SemanticNeighborAnalysisError(
                f"The {name} is missing columns: {', '.join(sorted(missing))}"
            )
        if dataframe[ID_COLUMN].duplicated().any():
            raise SemanticNeighborAnalysisError(
                f"The {name} contains duplicate {ID_COLUMN} values."
            )

    original_labels = train_original[
        [ID_COLUMN, CATEGORY_COLUMN, SECTION_COLUMN]
    ].rename(
        columns={
            CATEGORY_COLUMN: "original_category",
            SECTION_COLUMN: "original_section",
        }
    )
    llm_labels = train_llm[
        [ID_COLUMN, CATEGORY_COLUMN, SECTION_COLUMN]
    ].rename(
        columns={
            CATEGORY_COLUMN: "llm_category",
            SECTION_COLUMN: "llm_section",
        }
    )

    aligned = train_metadata[[ID_COLUMN, "embedding_row", HEADLINE_COLUMN]].merge(
        original_labels,
        on=ID_COLUMN,
        how="left",
        validate="one_to_one",
    ).merge(
        llm_labels,
        on=ID_COLUMN,
        how="left",
        validate="one_to_one",
    )

    label_columns = [
        "original_category",
        "original_section",
        "llm_category",
        "llm_section",
    ]
    if aligned[label_columns].isna().any().any():
        raise SemanticNeighborAnalysisError(
            "Could not align all original and LLM training labels to embeddings."
        )
    return aligned


# ---------------------------------------------------------------------------
# Nearest-neighbour analysis
# ---------------------------------------------------------------------------

def compute_neighbors(
    embeddings: np.ndarray,
    neighbor_count: int,
    n_jobs: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Find each article's nearest non-self neighbours by cosine distance."""
    row_count = embeddings.shape[0]
    if row_count < 2:
        raise SemanticNeighborAnalysisError(
            "At least two articles are required for nearest-neighbour analysis."
        )

    effective_count = min(neighbor_count, row_count - 1)
    if effective_count != neighbor_count:
        logger.warning(
            "Requested %d neighbours but only %d are available; using %d.",
            neighbor_count,
            row_count - 1,
            effective_count,
        )

    model = NearestNeighbors(
        n_neighbors=effective_count + 1,
        metric="cosine",
        n_jobs=n_jobs,
    )
    model.fit(embeddings)
    distances, indices = model.kneighbors(embeddings)

    # The first returned index is normally the query row itself. Remove self by
    # identity rather than assuming its position, then retain the requested count.
    neighbor_indices = np.empty((row_count, effective_count), dtype=int)
    neighbor_similarities = np.empty(
        (row_count, effective_count), dtype=np.float32
    )

    for row_index in range(row_count):
        candidates = [
            (int(index), float(distance))
            for index, distance in zip(indices[row_index], distances[row_index])
            if int(index) != row_index
        ]
        if len(candidates) < effective_count:
            raise SemanticNeighborAnalysisError(
                "Nearest-neighbour retrieval did not return enough non-self rows."
            )
        selected = candidates[:effective_count]
        neighbor_indices[row_index] = [item[0] for item in selected]
        neighbor_similarities[row_index] = [1.0 - item[1] for item in selected]

    return neighbor_indices, neighbor_similarities


def create_article_results(
    metadata: pd.DataFrame,
    neighbor_indices: np.ndarray,
    neighbor_similarities: np.ndarray,
    label_mapping: dict[str, str],
) -> pd.DataFrame:
    """Create one wide result row per article, matching the notebook format."""
    results = metadata[[ID_COLUMN, HEADLINE_COLUMN]].copy()

    for output_label in label_mapping:
        results[output_label] = metadata[label_mapping[output_label]].to_numpy()

    for rank in range(neighbor_indices.shape[1]):
        rank_number = rank + 1
        selected_indices = neighbor_indices[:, rank]
        results[f"neighbor_{rank_number}_index"] = metadata.iloc[
            selected_indices
        ][ID_COLUMN].to_numpy()
        results[f"neighbor_{rank_number}_headline"] = metadata.iloc[
            selected_indices
        ][HEADLINE_COLUMN].to_numpy()
        results[f"neighbor_{rank_number}_similarity"] = (
            neighbor_similarities[:, rank]
        )

    for output_label in label_mapping:
        source_column = label_mapping[output_label]
        labels = metadata[source_column].astype(str).to_numpy()
        same_label = labels[neighbor_indices] == labels[:, None]
        results[f"same_{output_label}_neighbor_ratio"] = same_label.mean(axis=1)

    results["mean_neighbor_similarity"] = neighbor_similarities.mean(axis=1)
    results["minimum_neighbor_similarity"] = neighbor_similarities.min(axis=1)
    results["maximum_neighbor_similarity"] = neighbor_similarities.max(axis=1)
    return results


def create_neighbor_pairs(
    metadata: pd.DataFrame,
    neighbor_indices: np.ndarray,
    neighbor_similarities: np.ndarray,
    label_mapping: dict[str, str],
    dataset_name: str,
) -> pd.DataFrame:
    """Create a long-format table containing one row per neighbour pair."""
    rows: list[dict[str, Any]] = []

    for article_row in range(len(metadata)):
        source = metadata.iloc[article_row]
        for rank, neighbor_row in enumerate(neighbor_indices[article_row], start=1):
            neighbor = metadata.iloc[int(neighbor_row)]
            row: dict[str, Any] = {
                "dataset": dataset_name,
                "article_embedding_row": article_row,
                "article_index": source[ID_COLUMN],
                "article_headline": source[HEADLINE_COLUMN],
                "neighbor_rank": rank,
                "neighbor_embedding_row": int(neighbor_row),
                "neighbor_index": neighbor[ID_COLUMN],
                "neighbor_headline": neighbor[HEADLINE_COLUMN],
                "cosine_similarity": float(
                    neighbor_similarities[article_row, rank - 1]
                ),
            }
            for output_label, source_column in label_mapping.items():
                article_label = source[source_column]
                neighbor_label = neighbor[source_column]
                row[f"article_{output_label}"] = article_label
                row[f"neighbor_{output_label}"] = neighbor_label
                row[f"same_{output_label}"] = bool(
                    str(article_label) == str(neighbor_label)
                )
            rows.append(row)

    return pd.DataFrame(rows)


def summarize_label_source(
    article_results: pd.DataFrame,
    dataset_name: str,
    label_mapping: dict[str, str],
) -> pd.DataFrame:
    """Summarize article-level agreement ratios for each label definition."""
    rows: list[dict[str, Any]] = []
    for output_label in label_mapping:
        ratio_column = f"same_{output_label}_neighbor_ratio"
        values = article_results[ratio_column]
        rows.append(
            {
                "dataset": dataset_name,
                "label_definition": output_label,
                "article_count": int(len(values)),
                "mean_neighbor_agreement": float(values.mean()),
                "median_neighbor_agreement": float(values.median()),
                "standard_deviation": float(values.std(ddof=1)),
                "minimum_neighbor_agreement": float(values.min()),
                "maximum_neighbor_agreement": float(values.max()),
                "perfect_agreement_article_ratio": float((values == 1.0).mean()),
                "zero_agreement_article_ratio": float((values == 0.0).mean()),
                "mean_cosine_similarity": float(
                    article_results["mean_neighbor_similarity"].mean()
                ),
            }
        )
    return pd.DataFrame(rows)


def summarize_by_class(
    metadata: pd.DataFrame,
    article_results: pd.DataFrame,
    label_mapping: dict[str, str],
    dataset_name: str,
) -> pd.DataFrame:
    """Aggregate neighbour consistency by label class."""
    rows: list[dict[str, Any]] = []

    for output_label, source_column in label_mapping.items():
        working = pd.DataFrame(
            {
                "label": metadata[source_column].astype(str).to_numpy(),
                "agreement": article_results[
                    f"same_{output_label}_neighbor_ratio"
                ].to_numpy(),
                "similarity": article_results[
                    "mean_neighbor_similarity"
                ].to_numpy(),
            }
        )
        for class_name, group in working.groupby("label", sort=True):
            rows.append(
                {
                    "dataset": dataset_name,
                    "label_definition": output_label,
                    "class": class_name,
                    "article_count": int(len(group)),
                    "mean_neighbor_agreement": float(group["agreement"].mean()),
                    "median_neighbor_agreement": float(
                        group["agreement"].median()
                    ),
                    "mean_cosine_similarity": float(group["similarity"].mean()),
                }
            )

    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Visualizations
# ---------------------------------------------------------------------------

def save_figure(path: Path, dpi: int) -> None:
    """Save and close the active figure."""
    path.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close()
    logger.info("Saved figure: %s", path)


def plot_similarity_distribution(
    pair_results: pd.DataFrame,
    output_path: Path,
    dpi: int,
) -> None:
    """Visualize cosine similarity across all retrieved neighbour pairs."""
    plt.figure(figsize=(10, 6))
    plt.hist(pair_results["cosine_similarity"], bins=40, edgecolor="black")
    plt.xlabel("Cosine similarity")
    plt.ylabel("Neighbour-pair count")
    plt.title("Distribution of Sentence-BERT Neighbour Similarities")
    plt.grid(axis="y", alpha=0.25)
    save_figure(output_path, dpi)


def plot_summary_agreement(
    summary: pd.DataFrame,
    output_path: Path,
    dpi: int,
    title: str,
) -> None:
    """Plot mean neighbour agreement for each label definition."""
    plot_data = summary.sort_values("mean_neighbor_agreement", ascending=True)
    plt.figure(figsize=(10, max(5, 0.55 * len(plot_data) + 2)))
    bars = plt.barh(
        plot_data["label_definition"],
        plot_data["mean_neighbor_agreement"],
    )
    plt.xlim(0.0, 1.0)
    plt.xlabel("Mean same-label neighbour ratio")
    plt.ylabel("Label definition")
    plt.title(title)
    plt.grid(axis="x", alpha=0.25)
    for bar, value in zip(bars, plot_data["mean_neighbor_agreement"]):
        plt.text(
            min(float(value) + 0.015, 0.96),
            bar.get_y() + bar.get_height() / 2,
            f"{value:.3f}",
            va="center",
        )
    save_figure(output_path, dpi)


def plot_class_consistency(
    class_summary: pd.DataFrame,
    label_definition: str,
    output_path: Path,
    dpi: int,
    top_classes: int,
) -> None:
    """Plot class-level consistency, retaining the most frequent classes."""
    subset = class_summary[
        class_summary["label_definition"] == label_definition
    ].copy()
    if subset.empty:
        return

    subset = subset.nlargest(top_classes, "article_count")
    subset = subset.sort_values("mean_neighbor_agreement", ascending=True)

    plt.figure(figsize=(11, max(6, 0.38 * len(subset) + 2)))
    bars = plt.barh(subset["class"], subset["mean_neighbor_agreement"])
    plt.xlim(0.0, 1.0)
    plt.xlabel("Mean same-label neighbour ratio")
    plt.ylabel("Class")
    plt.title(
        f"Semantic Neighbour Consistency by {label_definition.replace('_', ' ').title()}"
    )
    plt.grid(axis="x", alpha=0.25)
    for bar, value, count in zip(
        bars,
        subset["mean_neighbor_agreement"],
        subset["article_count"],
    ):
        plt.text(
            min(float(value) + 0.012, 0.93),
            bar.get_y() + bar.get_height() / 2,
            f"{value:.2f} (n={int(count)})",
            va="center",
            fontsize=8,
        )
    save_figure(output_path, dpi)


def plot_agreement_distribution(
    article_results: pd.DataFrame,
    label_definitions: list[str],
    output_path: Path,
    dpi: int,
    title: str,
) -> None:
    """Plot the distribution of article-level neighbour-agreement ratios."""
    positions = np.arange(len(label_definitions))
    means = [
        article_results[f"same_{label}_neighbor_ratio"].mean()
        for label in label_definitions
    ]
    medians = [
        article_results[f"same_{label}_neighbor_ratio"].median()
        for label in label_definitions
    ]
    width = 0.38

    plt.figure(figsize=(11, 6))
    plt.bar(positions - width / 2, means, width, label="Mean")
    plt.bar(positions + width / 2, medians, width, label="Median")
    plt.xticks(
        positions,
        [label.replace("_", " ").title() for label in label_definitions],
        rotation=20,
        ha="right",
    )
    plt.ylim(0.0, 1.0)
    plt.ylabel("Same-label neighbour ratio")
    plt.xlabel("Label definition")
    plt.title(title)
    plt.legend()
    plt.grid(axis="y", alpha=0.25)
    save_figure(output_path, dpi)


# ---------------------------------------------------------------------------
# Pipeline stage
# ---------------------------------------------------------------------------

def run_semantic_neighbor_analysis(
    config_path: Path = CONFIG_PATH,
) -> None:
    """Run the complete semantic nearest-neighbour analysis stage."""
    logger.info("Starting semantic nearest-neighbour analysis.")

    config = load_config(config_path)
    settings = get_neighbor_settings(config)
    dataset_config = config["dataset"]

    train_original_path = resolve_project_path(dataset_config["train_file"])
    train_llm_path = resolve_project_path(dataset_config["llm_train_file"])

    require_files(
        [
            FULL_EMBEDDINGS_PATH,
            TRAIN_EMBEDDINGS_PATH,
            FULL_METADATA_PATH,
            TRAIN_METADATA_PATH,
            MANIFEST_PATH,
            train_original_path,
            train_llm_path,
        ]
    )

    TABLE_DIRECTORY.mkdir(parents=True, exist_ok=True)
    FIGURE_DIRECTORY.mkdir(parents=True, exist_ok=True)

    manifest = load_manifest()
    expected_dimension = manifest.get("embedding_dimension")
    if expected_dimension is not None:
        expected_dimension = int(expected_dimension)

    full_metadata = read_csv(FULL_METADATA_PATH)
    train_metadata = read_csv(TRAIN_METADATA_PATH)
    train_original = read_csv(train_original_path)
    train_llm = read_csv(train_llm_path)

    validate_metadata(full_metadata, "full-dataset")
    validate_metadata(train_metadata, "training")

    full_embeddings = np.load(FULL_EMBEDDINGS_PATH, mmap_mode="r")
    train_embeddings = np.load(TRAIN_EMBEDDINGS_PATH, mmap_mode="r")
    validate_embeddings(
        full_embeddings,
        full_metadata,
        "full-dataset",
        expected_dimension,
    )
    validate_embeddings(
        train_embeddings,
        train_metadata,
        "training",
        expected_dimension,
    )

    logger.info(
        "Finding %d nearest neighbours for %d full-dataset articles.",
        settings.neighbor_count,
        len(full_metadata),
    )
    full_indices, full_similarities = compute_neighbors(
        full_embeddings,
        neighbor_count=settings.neighbor_count,
        n_jobs=settings.n_jobs,
    )

    full_label_mapping = {
        "category": CATEGORY_COLUMN,
        "section": SECTION_COLUMN,
    }
    full_article_results = create_article_results(
        full_metadata,
        full_indices,
        full_similarities,
        full_label_mapping,
    )
    full_pair_results = create_neighbor_pairs(
        full_metadata,
        full_indices,
        full_similarities,
        full_label_mapping,
        dataset_name="full_original",
    )
    full_summary = summarize_label_source(
        full_article_results,
        dataset_name="full_original",
        label_mapping=full_label_mapping,
    )
    full_class_summary = summarize_by_class(
        full_metadata,
        full_article_results,
        full_label_mapping,
        dataset_name="full_original",
    )

    aligned_train = align_training_labels(
        train_metadata,
        train_original,
        train_llm,
    )
    # Attach aligned labels to metadata while preserving embedding-row order.
    train_analysis_metadata = train_metadata.copy()
    for column in (
        "original_category",
        "original_section",
        "llm_category",
        "llm_section",
    ):
        train_analysis_metadata[column] = aligned_train[column].to_numpy()

    logger.info(
        "Finding %d nearest neighbours for %d training articles.",
        settings.neighbor_count,
        len(train_analysis_metadata),
    )
    train_indices, train_similarities = compute_neighbors(
        train_embeddings,
        neighbor_count=settings.neighbor_count,
        n_jobs=settings.n_jobs,
    )
    train_label_mapping = {
        "original_category": "original_category",
        "llm_category": "llm_category",
        "original_section": "original_section",
        "llm_section": "llm_section",
    }
    train_article_results = create_article_results(
        train_analysis_metadata,
        train_indices,
        train_similarities,
        train_label_mapping,
    )
    train_pair_results = create_neighbor_pairs(
        train_analysis_metadata,
        train_indices,
        train_similarities,
        train_label_mapping,
        dataset_name="training_label_comparison",
    )
    train_summary = summarize_label_source(
        train_article_results,
        dataset_name="training_label_comparison",
        label_mapping=train_label_mapping,
    )
    train_class_summary = summarize_by_class(
        train_analysis_metadata,
        train_article_results,
        train_label_mapping,
        dataset_name="training_label_comparison",
    )

    combined_summary = pd.concat(
        [full_summary, train_summary],
        ignore_index=True,
    )

    write_csv(
        full_article_results,
        TABLE_DIRECTORY / "full_neighbor_results.csv",
    )
    write_csv(
        full_pair_results,
        TABLE_DIRECTORY / "full_neighbor_pairs.csv",
    )
    write_csv(
        full_class_summary,
        TABLE_DIRECTORY / "full_class_consistency.csv",
    )
    write_csv(
        train_article_results,
        TABLE_DIRECTORY / "train_neighbor_results.csv",
    )
    write_csv(
        train_pair_results,
        TABLE_DIRECTORY / "train_neighbor_pairs.csv",
    )
    write_csv(
        train_summary,
        TABLE_DIRECTORY / "train_label_source_summary.csv",
    )
    write_csv(
        train_class_summary,
        TABLE_DIRECTORY / "train_class_consistency.csv",
    )
    write_csv(
        combined_summary,
        TABLE_DIRECTORY / "semantic_neighbor_summary.csv",
    )

    plot_similarity_distribution(
        full_pair_results,
        FIGURE_DIRECTORY / "full_similarity_distribution.png",
        settings.figure_dpi,
    )
    plot_summary_agreement(
        full_summary,
        FIGURE_DIRECTORY / "full_category_section_consistency.png",
        settings.figure_dpi,
        "Semantic Neighbour Consistency for Original CNN Labels",
    )
    plot_summary_agreement(
        train_summary,
        FIGURE_DIRECTORY / "cnn_vs_llm_label_consistency.png",
        settings.figure_dpi,
        "Semantic Neighbour Consistency: CNN vs LLM Labels",
    )
    plot_agreement_distribution(
        train_article_results,
        list(train_label_mapping),
        FIGURE_DIRECTORY / "cnn_vs_llm_mean_median_consistency.png",
        settings.figure_dpi,
        "Mean and Median Same-Label Neighbour Ratios",
    )

    for label_definition in full_label_mapping:
        plot_class_consistency(
            full_class_summary,
            label_definition,
            FIGURE_DIRECTORY
            / f"full_{label_definition}_class_consistency.png",
            settings.figure_dpi,
            settings.top_classes,
        )

    for label_definition in train_label_mapping:
        plot_class_consistency(
            train_class_summary,
            label_definition,
            FIGURE_DIRECTORY
            / f"train_{label_definition}_class_consistency.png",
            settings.figure_dpi,
            settings.top_classes,
        )

    logger.info(
        "Semantic neighbour analysis completed. Tables: %s; figures: %s.",
        TABLE_DIRECTORY,
        FIGURE_DIRECTORY,
    )


if __name__ == "__main__":
    try:
        run_semantic_neighbor_analysis()
    except SemanticNeighborAnalysisError:
        logger.exception("Semantic nearest-neighbour analysis failed.")
        raise
    except Exception as error:
        logger.exception(
            "Semantic nearest-neighbour analysis failed unexpectedly."
        )
        raise SemanticNeighborAnalysisError(
            "Semantic nearest-neighbour analysis failed unexpectedly."
        ) from error
