"""
10_train_embedding_models.py

Train supervised classifiers using the Sentence-BERT embeddings generated by
08_generate_sentence_embeddings.py.

This stage integrates the embedding-based classification methodology developed
in the project notebook. The notebook's five classifiers are retained:

- Logistic Regression
- Linear Support Vector Machine
- Random Forest
- XGBoost
- Small Neural Network

Each classifier is trained under four experimental conditions:

1. Category prediction using original CNN labels.
2. Category prediction using LLM-generated labels.
3. Section prediction using original CNN labels.
4. Section prediction using LLM-generated labels.

The Sentence-BERT embedding matrix is shared across all conditions. Only the
training labels change. A condition-specific LabelEncoder is stored with every
trained model so that non-contiguous or rare Section labels do not prevent
training and later evaluation.

Inputs:
- data/interim/train_original.csv
- data/interim/train_llm_labeled.csv
- data/processed/sentence_embeddings/train_embeddings.npy
- data/processed/sentence_embeddings/train_metadata.csv
- data/processed/sentence_embeddings/embedding_manifest.json

Outputs:
- models/sentence_bert/category/real/*.pkl
- models/sentence_bert/category/llm/*.pkl
- models/sentence_bert/section/real/*.pkl
- models/sentence_bert/section/llm/*.pkl
- results/tables/sentence_bert/embedding_model_training_summary.csv
- models/sentence_bert/training_manifest.json
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import pickle
import sys
import time
from typing import Any, Callable

import numpy as np
import pandas as pd
import yaml
from sklearn.base import ClassifierMixin
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier


# ---------------------------------------------------------------------------
# Project paths and imports
# ---------------------------------------------------------------------------

SRC_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SRC_DIR.parent
CONFIG_PATH = PROJECT_ROOT / "config" / "config.yaml"

PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"
EMBEDDING_DIRECTORY = PROCESSED_DATA_DIR / "sentence_embeddings"
TRAIN_EMBEDDINGS_PATH = EMBEDDING_DIRECTORY / "train_embeddings.npy"
TRAIN_METADATA_PATH = EMBEDDING_DIRECTORY / "train_metadata.csv"
EMBEDDING_MANIFEST_PATH = EMBEDDING_DIRECTORY / "embedding_manifest.json"

MODEL_DIRECTORY = PROJECT_ROOT / "models" / "sentence_bert"
TRAINING_MANIFEST_PATH = MODEL_DIRECTORY / "training_manifest.json"
TRAINING_SUMMARY_PATH = (
    PROJECT_ROOT
    / "results"
    / "tables"
    / "sentence_bert"
    / "embedding_model_training_summary.csv"
)

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from utils.io import read_csv, write_csv
from utils.logging import get_logger


logger = get_logger(
    name=__name__,
    log_directory=PROJECT_ROOT / "logs",
    log_file="project.log",
)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ID_COLUMN = "Index"
CATEGORY_COLUMN = "Category"
SECTION_COLUMN = "Section"

LABEL_SOURCE_REAL = "real"
LABEL_SOURCE_LLM = "llm"
TARGET_CATEGORY = "category"
TARGET_SECTION = "section"

MODEL_LOGISTIC = "logistic"
MODEL_SVM = "svm"
MODEL_RANDOM_FOREST = "random_forest"
MODEL_XGBOOST = "xgboost"
MODEL_NEURAL_NETWORK = "neural_network"

SUPPORTED_MODELS: tuple[str, ...] = (
    MODEL_LOGISTIC,
    MODEL_SVM,
    MODEL_RANDOM_FOREST,
    MODEL_XGBOOST,
    MODEL_NEURAL_NETWORK,
)

MODEL_DISPLAY_NAMES: dict[str, str] = {
    MODEL_LOGISTIC: "Logistic Regression",
    MODEL_SVM: "Linear SVM",
    MODEL_RANDOM_FOREST: "Random Forest",
    MODEL_XGBOOST: "XGBoost",
    MODEL_NEURAL_NETWORK: "Small Neural Network",
}

DEFAULT_MODEL_SETTINGS: dict[str, dict[str, Any]] = {
    # These defaults reproduce the models used in the partner notebook.
    MODEL_LOGISTIC: {
        "enabled": True,
        "max_iter": 3000,
        "class_weight": "balanced",
    },
    MODEL_SVM: {
        "enabled": True,
        "class_weight": "balanced",
    },
    MODEL_RANDOM_FOREST: {
        "enabled": True,
        "n_estimators": 400,
        "class_weight": "balanced_subsample",
        "n_jobs": -1,
    },
    MODEL_XGBOOST: {
        "enabled": True,
        "n_estimators": 350,
        "max_depth": 6,
        "learning_rate": 0.05,
        "subsample": 0.85,
        "colsample_bytree": 0.85,
        "eval_metric": "mlogloss",
        "n_jobs": -1,
    },
    MODEL_NEURAL_NETWORK: {
        "enabled": True,
        "hidden_layer_sizes": (256, 64),
        "early_stopping": True,
        "max_iter": 300,
    },
}


class EmbeddingModelTrainingError(RuntimeError):
    """Raised when embedding-based models cannot be trained safely."""


@dataclass(frozen=True)
class TrainingCondition:
    """One target and label-source combination."""

    target: str
    label_source: str
    label_column: str


@dataclass(frozen=True)
class ModelSettings:
    """Resolved configuration for one classifier."""

    model_name: str
    enabled: bool
    parameters: dict[str, Any]


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def load_config(config_path: Path) -> dict[str, Any]:
    """Load and validate the project configuration."""
    if not config_path.exists():
        raise EmbeddingModelTrainingError(
            f"Configuration file not found: {config_path}"
        )

    try:
        with config_path.open("r", encoding="utf-8") as file:
            config = yaml.safe_load(file)
    except yaml.YAMLError as error:
        raise EmbeddingModelTrainingError(
            f"Could not parse the configuration file: {error}"
        ) from error

    if not isinstance(config, dict):
        raise EmbeddingModelTrainingError(
            "The configuration file must contain a YAML mapping."
        )

    dataset_config = config.get("dataset")
    project_config = config.get("project")

    if not isinstance(dataset_config, dict):
        raise EmbeddingModelTrainingError(
            "The configuration must contain a 'dataset' section."
        )

    if not isinstance(project_config, dict):
        raise EmbeddingModelTrainingError(
            "The configuration must contain a 'project' section."
        )

    required_dataset_settings = {"train_file", "llm_train_file"}
    missing_dataset_settings = required_dataset_settings - set(dataset_config)
    if missing_dataset_settings:
        missing = ", ".join(sorted(missing_dataset_settings))
        raise EmbeddingModelTrainingError(
            f"Missing dataset settings in config.yaml: {missing}"
        )

    if "random_seed" not in project_config:
        raise EmbeddingModelTrainingError(
            "Missing project.random_seed in config.yaml."
        )

    if not isinstance(project_config["random_seed"], int):
        raise EmbeddingModelTrainingError(
            "project.random_seed must be an integer."
        )

    return config


def resolve_project_path(configured_path: str) -> Path:
    """Resolve a configured path relative to the project root."""
    path = Path(configured_path)
    return path if path.is_absolute() else PROJECT_ROOT / path


def get_model_settings(config: dict[str, Any]) -> list[ModelSettings]:
    """
    Resolve embedding-classifier settings.

    The future config.yaml extension may provide an ``embedding_classifiers``
    section. Until that section is added, notebook-equivalent defaults are used,
    allowing this file to work without modifying the current configuration.
    """
    configured = config.get("embedding_classifiers", {})
    if configured is None:
        configured = {}
    if not isinstance(configured, dict):
        raise EmbeddingModelTrainingError(
            "embedding_classifiers must be a YAML mapping when provided."
        )

    resolved: list[ModelSettings] = []

    for model_name in SUPPORTED_MODELS:
        defaults = dict(DEFAULT_MODEL_SETTINGS[model_name])
        user_setting = configured.get(model_name)

        if user_setting is None:
            merged = defaults
        elif isinstance(user_setting, bool):
            merged = defaults
            merged["enabled"] = user_setting
        elif isinstance(user_setting, dict):
            merged = defaults
            merged.update(user_setting)
        else:
            raise EmbeddingModelTrainingError(
                f"embedding_classifiers.{model_name} must be a Boolean "
                "or YAML mapping."
            )

        enabled = merged.pop("enabled", True)
        if not isinstance(enabled, bool):
            raise EmbeddingModelTrainingError(
                f"embedding_classifiers.{model_name}.enabled must be Boolean."
            )

        if model_name == MODEL_NEURAL_NETWORK:
            hidden_layers = merged.get("hidden_layer_sizes")
            if isinstance(hidden_layers, list):
                merged["hidden_layer_sizes"] = tuple(hidden_layers)

        resolved.append(
            ModelSettings(
                model_name=model_name,
                enabled=enabled,
                parameters=merged,
            )
        )

    if not any(setting.enabled for setting in resolved):
        raise EmbeddingModelTrainingError(
            "At least one embedding classifier must be enabled."
        )

    return resolved


# ---------------------------------------------------------------------------
# Input loading and validation
# ---------------------------------------------------------------------------

def load_training_dataset(file_path: Path, dataset_name: str) -> pd.DataFrame:
    """Load and validate one training dataset."""
    if not file_path.exists():
        raise EmbeddingModelTrainingError(
            f"{dataset_name} not found: {file_path}"
        )

    dataframe = read_csv(file_path)
    if dataframe.empty:
        raise EmbeddingModelTrainingError(
            f"{dataset_name} contains no rows."
        )

    required_columns = {ID_COLUMN, CATEGORY_COLUMN, SECTION_COLUMN}
    missing_columns = required_columns - set(dataframe.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise EmbeddingModelTrainingError(
            f"{dataset_name} is missing required columns: {missing}"
        )

    if dataframe[ID_COLUMN].isna().any():
        raise EmbeddingModelTrainingError(
            f"{dataset_name} contains missing {ID_COLUMN} values."
        )
    if not dataframe[ID_COLUMN].is_unique:
        raise EmbeddingModelTrainingError(
            f"{dataset_name} contains duplicated {ID_COLUMN} values."
        )

    for column in (CATEGORY_COLUMN, SECTION_COLUMN):
        labels = dataframe[column]
        if labels.isna().any():
            raise EmbeddingModelTrainingError(
                f"{dataset_name} contains missing {column} labels."
            )
        if labels.astype(str).str.strip().eq("").any():
            raise EmbeddingModelTrainingError(
                f"{dataset_name} contains blank {column} labels."
            )

    logger.info("Loaded %s: %d rows.", dataset_name, len(dataframe))
    return dataframe


def validate_training_alignment(
    original_training: pd.DataFrame,
    llm_training: pd.DataFrame,
) -> None:
    """Verify that label source is the only difference between datasets."""
    if list(original_training.columns) != list(llm_training.columns):
        raise EmbeddingModelTrainingError(
            "The original-label and LLM-label datasets have different columns "
            "or column order."
        )
    if len(original_training) != len(llm_training):
        raise EmbeddingModelTrainingError(
            "The original-label and LLM-label datasets have different row counts."
        )
    if list(original_training[ID_COLUMN]) != list(llm_training[ID_COLUMN]):
        raise EmbeddingModelTrainingError(
            "The original-label and LLM-label datasets are not in the same row order."
        )

    non_label_columns = [
        column
        for column in original_training.columns
        if column not in {CATEGORY_COLUMN, SECTION_COLUMN}
    ]

    try:
        pd.testing.assert_frame_equal(
            original_training[non_label_columns].reset_index(drop=True),
            llm_training[non_label_columns].reset_index(drop=True),
            check_dtype=False,
            check_like=False,
        )
    except AssertionError as error:
        raise EmbeddingModelTrainingError(
            "The training datasets differ in one or more non-label values."
        ) from error

    logger.info("Original-label and LLM-label training datasets are aligned.")


def load_embeddings(expected_rows: int) -> np.ndarray:
    """Load and validate the training Sentence-BERT matrix."""
    if not TRAIN_EMBEDDINGS_PATH.exists():
        raise EmbeddingModelTrainingError(
            "Training embeddings were not found. Run "
            "08_generate_sentence_embeddings.py first: "
            f"{TRAIN_EMBEDDINGS_PATH}"
        )

    try:
        embeddings = np.load(TRAIN_EMBEDDINGS_PATH, allow_pickle=False)
    except (OSError, ValueError) as error:
        raise EmbeddingModelTrainingError(
            f"Could not load training embeddings: {error}"
        ) from error

    if embeddings.ndim != 2:
        raise EmbeddingModelTrainingError(
            "Training embeddings must be a two-dimensional matrix."
        )
    if embeddings.shape[0] != expected_rows:
        raise EmbeddingModelTrainingError(
            "Embedding row count does not match the training datasets. "
            f"Embeddings: {embeddings.shape[0]}; rows: {expected_rows}."
        )
    if embeddings.shape[1] <= 0:
        raise EmbeddingModelTrainingError(
            "Training embeddings contain no features."
        )
    if not np.issubdtype(embeddings.dtype, np.number):
        raise EmbeddingModelTrainingError(
            "Training embeddings must contain numeric values."
        )
    if not np.isfinite(embeddings).all():
        raise EmbeddingModelTrainingError(
            "Training embeddings contain NaN or infinite values."
        )

    logger.info(
        "Loaded training embeddings: %d rows and %d dimensions.",
        embeddings.shape[0],
        embeddings.shape[1],
    )
    return np.asarray(embeddings, dtype=np.float32)


def validate_embedding_metadata(training: pd.DataFrame) -> None:
    """Confirm that embedding rows align with dataset rows."""
    if not TRAIN_METADATA_PATH.exists():
        raise EmbeddingModelTrainingError(
            "Embedding metadata was not found. Run "
            "08_generate_sentence_embeddings.py first: "
            f"{TRAIN_METADATA_PATH}"
        )

    metadata = read_csv(TRAIN_METADATA_PATH)
    required_columns = {ID_COLUMN, "embedding_row"}
    missing_columns = required_columns - set(metadata.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise EmbeddingModelTrainingError(
            f"Embedding metadata is missing columns: {missing}"
        )

    if len(metadata) != len(training):
        raise EmbeddingModelTrainingError(
            "Embedding metadata row count does not match the training dataset."
        )

    expected_rows = np.arange(len(metadata), dtype=int)
    actual_rows = pd.to_numeric(
        metadata["embedding_row"], errors="coerce"
    ).to_numpy()
    if np.isnan(actual_rows).any() or not np.array_equal(
        actual_rows.astype(int), expected_rows
    ):
        raise EmbeddingModelTrainingError(
            "Embedding metadata has invalid or reordered embedding_row values."
        )

    if list(metadata[ID_COLUMN].astype(str)) != list(
        training[ID_COLUMN].astype(str)
    ):
        raise EmbeddingModelTrainingError(
            "Embedding metadata does not align with the training dataset IDs."
        )

    logger.info("Embedding metadata is aligned with the training dataset.")


def load_embedding_manifest() -> dict[str, Any]:
    """Load the embedding-stage manifest when available."""
    if not EMBEDDING_MANIFEST_PATH.exists():
        logger.warning(
            "Embedding manifest not found; model training will continue after "
            "matrix and metadata validation."
        )
        return {}

    try:
        with EMBEDDING_MANIFEST_PATH.open("r", encoding="utf-8") as file:
            manifest = json.load(file)
    except (OSError, json.JSONDecodeError) as error:
        raise EmbeddingModelTrainingError(
            f"Could not read the embedding manifest: {error}"
        ) from error

    if not isinstance(manifest, dict):
        raise EmbeddingModelTrainingError(
            "The embedding manifest must contain a JSON object."
        )
    return manifest


# ---------------------------------------------------------------------------
# Model construction
# ---------------------------------------------------------------------------

def create_xgboost_classifier(
    parameters: dict,
    random_seed: int,
):
    """Create an XGBoost classifier without duplicating random_state."""

    xgboost_parameters = dict(parameters)
    xgboost_parameters.setdefault("random_state", random_seed)

    return XGBClassifier(**xgboost_parameters)


def build_classifier(
    setting: ModelSettings,
    random_seed: int,
) -> ClassifierMixin:
    """Construct a fresh classifier for one training condition."""
    parameters = dict(setting.parameters)

    # Preserve the notebook's deterministic setup unless explicitly overridden.
    parameters.setdefault("random_state", random_seed)

    constructors: dict[str, Callable[..., ClassifierMixin]] = {
        MODEL_LOGISTIC: LogisticRegression,
        MODEL_SVM: LinearSVC,
        MODEL_RANDOM_FOREST: RandomForestClassifier,
        MODEL_NEURAL_NETWORK: MLPClassifier,
    }

    try:
        if setting.model_name == MODEL_XGBOOST:
            return create_xgboost_classifier(parameters, random_seed)
        return constructors[setting.model_name](**parameters)
    except TypeError as error:
        raise EmbeddingModelTrainingError(
            f"Invalid parameters for {setting.model_name}: {error}"
        ) from error


# ---------------------------------------------------------------------------
# Training and persistence
# ---------------------------------------------------------------------------

def prepare_labels(
    dataframe: pd.DataFrame,
    label_column: str,
) -> tuple[np.ndarray, LabelEncoder]:
    """Encode labels contiguously for all supported classifiers."""
    labels = dataframe[label_column].astype(str).str.strip().to_numpy()
    encoder = LabelEncoder()
    encoded = encoder.fit_transform(labels)

    if len(encoder.classes_) < 2:
        raise EmbeddingModelTrainingError(
            f"{label_column} requires at least two observed classes for training."
        )

    return encoded.astype(np.int64), encoder


def model_output_path(
    target: str,
    label_source: str,
    model_name: str,
) -> Path:
    """Return the artifact path for one trained model bundle."""
    return MODEL_DIRECTORY / target / label_source / f"{model_name}.pkl"


def save_pickle_atomic(value: Any, output_path: Path) -> None:
    """Serialize a Python object through an atomic file replacement."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_suffix(output_path.suffix + ".tmp")

    try:
        with temporary_path.open("wb") as file:
            pickle.dump(value, file, protocol=pickle.HIGHEST_PROTOCOL)
        temporary_path.replace(output_path)
    except (OSError, pickle.PickleError) as error:
        temporary_path.unlink(missing_ok=True)
        raise EmbeddingModelTrainingError(
            f"Could not save model artifact {output_path}: {error}"
        ) from error


def train_one_model(
    embeddings: np.ndarray,
    labels: np.ndarray,
    label_encoder: LabelEncoder,
    condition: TrainingCondition,
    setting: ModelSettings,
    random_seed: int,
    embedding_manifest: dict[str, Any],
) -> dict[str, Any]:
    """Train and save one model bundle, returning a summary row."""
    classifier = build_classifier(setting, random_seed)
    output_path = model_output_path(
        condition.target,
        condition.label_source,
        setting.model_name,
    )

    logger.info(
        "Training %s for %s using %s labels (%d classes).",
        MODEL_DISPLAY_NAMES[setting.model_name],
        condition.target,
        condition.label_source,
        len(label_encoder.classes_),
    )

    start_time = time.perf_counter()
    try:
        classifier.fit(embeddings, labels)
    except Exception as error:
        raise EmbeddingModelTrainingError(
            f"Training failed for {setting.model_name}, {condition.target}, "
            f"{condition.label_source}: {error}"
        ) from error
    elapsed_seconds = time.perf_counter() - start_time

    bundle = {
        "artifact_version": "1.0",
        "representation": "sentence_bert",
        "model_name": setting.model_name,
        "model_display_name": MODEL_DISPLAY_NAMES[setting.model_name],
        "target": condition.target,
        "label_source": condition.label_source,
        "label_column": condition.label_column,
        "classifier": classifier,
        "label_encoder": label_encoder,
        "classes": [str(value) for value in label_encoder.classes_],
        "parameters": setting.parameters,
        "random_seed": random_seed,
        "training_rows": int(embeddings.shape[0]),
        "embedding_dimension": int(embeddings.shape[1]),
        "embedding_model_name": embedding_manifest.get("model_name"),
        "trained_at_utc": datetime.now(timezone.utc).isoformat(),
        "training_time_seconds": elapsed_seconds,
    }
    save_pickle_atomic(bundle, output_path)

    logger.info(
        "Saved %s in %.3f seconds: %s",
        MODEL_DISPLAY_NAMES[setting.model_name],
        elapsed_seconds,
        output_path,
    )

    return {
        "representation": "Sentence-BERT",
        "target": condition.target,
        "label_source": condition.label_source,
        "model": setting.model_name,
        "model_display_name": MODEL_DISPLAY_NAMES[setting.model_name],
        "training_rows": int(embeddings.shape[0]),
        "embedding_dimension": int(embeddings.shape[1]),
        "observed_classes": int(len(label_encoder.classes_)),
        "class_labels": " | ".join(str(value) for value in label_encoder.classes_),
        "training_time_seconds": elapsed_seconds,
        "model_path": str(output_path.relative_to(PROJECT_ROOT)),
        "status": "success",
    }


def write_json_atomic(value: dict[str, Any], output_path: Path) -> None:
    """Write a formatted JSON object atomically."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_suffix(output_path.suffix + ".tmp")
    try:
        with temporary_path.open("w", encoding="utf-8") as file:
            json.dump(value, file, indent=2, sort_keys=True)
            file.write("\n")
        temporary_path.replace(output_path)
    except (OSError, TypeError) as error:
        temporary_path.unlink(missing_ok=True)
        raise EmbeddingModelTrainingError(
            f"Could not save JSON output {output_path}: {error}"
        ) from error


# ---------------------------------------------------------------------------
# Pipeline stage
# ---------------------------------------------------------------------------

def run_embedding_model_training(config_path: Path = CONFIG_PATH) -> None:
    """Run all enabled Sentence-BERT model-training experiments."""
    logger.info("Starting Sentence-BERT model training.")

    config = load_config(config_path)
    dataset_config = config["dataset"]
    random_seed = int(config["project"]["random_seed"])
    np.random.seed(random_seed)

    original_training_path = resolve_project_path(
        str(dataset_config["train_file"])
    )
    llm_training_path = resolve_project_path(
        str(dataset_config["llm_train_file"])
    )

    original_training = load_training_dataset(
        original_training_path,
        "original-label training dataset",
    )
    llm_training = load_training_dataset(
        llm_training_path,
        "LLM-label training dataset",
    )
    validate_training_alignment(original_training, llm_training)
    validate_embedding_metadata(original_training)

    embeddings = load_embeddings(expected_rows=len(original_training))
    embedding_manifest = load_embedding_manifest()
    settings = get_model_settings(config)

    conditions: tuple[tuple[TrainingCondition, pd.DataFrame], ...] = (
        (
            TrainingCondition(
                target=TARGET_CATEGORY,
                label_source=LABEL_SOURCE_REAL,
                label_column=CATEGORY_COLUMN,
            ),
            original_training,
        ),
        (
            TrainingCondition(
                target=TARGET_CATEGORY,
                label_source=LABEL_SOURCE_LLM,
                label_column=CATEGORY_COLUMN,
            ),
            llm_training,
        ),
        (
            TrainingCondition(
                target=TARGET_SECTION,
                label_source=LABEL_SOURCE_REAL,
                label_column=SECTION_COLUMN,
            ),
            original_training,
        ),
        (
            TrainingCondition(
                target=TARGET_SECTION,
                label_source=LABEL_SOURCE_LLM,
                label_column=SECTION_COLUMN,
            ),
            llm_training,
        ),
    )

    summary_rows: list[dict[str, Any]] = []
    stage_start = time.perf_counter()

    for condition, dataframe in conditions:
        labels, label_encoder = prepare_labels(
            dataframe,
            condition.label_column,
        )

        class_counts = pd.Series(labels).value_counts()
        logger.info(
            "%s/%s label distribution: %d classes; minimum class count=%d; "
            "maximum class count=%d.",
            condition.target,
            condition.label_source,
            len(class_counts),
            int(class_counts.min()),
            int(class_counts.max()),
        )

        for setting in settings:
            if not setting.enabled:
                logger.info(
                    "Skipping disabled embedding classifier: %s.",
                    setting.model_name,
                )
                continue

            summary_rows.append(
                train_one_model(
                    embeddings=embeddings,
                    labels=labels,
                    label_encoder=label_encoder,
                    condition=condition,
                    setting=setting,
                    random_seed=random_seed,
                    embedding_manifest=embedding_manifest,
                )
            )

    total_elapsed = time.perf_counter() - stage_start
    summary = pd.DataFrame(summary_rows)
    if summary.empty:
        raise EmbeddingModelTrainingError(
            "No embedding models were trained."
        )

    write_csv(summary, TRAINING_SUMMARY_PATH)

    manifest = {
        "artifact_version": "1.0",
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "representation": "sentence_bert",
        "random_seed": random_seed,
        "training_rows": int(embeddings.shape[0]),
        "embedding_dimension": int(embeddings.shape[1]),
        "embedding_model_name": embedding_manifest.get("model_name"),
        "total_models_trained": int(len(summary)),
        "total_training_time_seconds": total_elapsed,
        "conditions": [
            asdict(condition)
            for condition, _ in conditions
        ],
        "enabled_models": [
            {
                "model_name": setting.model_name,
                "display_name": MODEL_DISPLAY_NAMES[setting.model_name],
                "parameters": setting.parameters,
            }
            for setting in settings
            if setting.enabled
        ],
        "outputs": {
            "model_directory": str(MODEL_DIRECTORY.relative_to(PROJECT_ROOT)),
            "training_summary": str(
                TRAINING_SUMMARY_PATH.relative_to(PROJECT_ROOT)
            ),
        },
    }
    write_json_atomic(manifest, TRAINING_MANIFEST_PATH)

    logger.info(
        "Sentence-BERT model training completed: %d models in %.3f seconds.",
        len(summary),
        total_elapsed,
    )


if __name__ == "__main__":
    try:
        run_embedding_model_training()
    except EmbeddingModelTrainingError:
        logger.exception("Sentence-BERT model training failed.")
        raise
    except Exception:
        logger.exception(
            "Sentence-BERT model training failed unexpectedly."
        )
        raise
